apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
data:
  DB_URL: mongodb://root:{{.Values.mongodb.auth.rootPassword}}@{{ .Release.Name }}-mongodb:27017
  ENVIRONMENT: prod
  MESSAGE_LOG_CATEGORIES: {{ .Values.messageLogs }}
  COMMUNITY_RELEASE_CHANNELS: {{ .Values.releaseChannels }}
  STATUS_CHANNEL: '{{ .Values.statusChannel }}'
