apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
data:
  # Metricity
  DATABASE_URI: postgres://postgres:stats@{{ .Chart.Name }}-postgresql/stats
  # BOT_TOKEN: secret value
  
  # Metabase
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: metabase
  MB_DB_PORT: '5432'
  MB_DB_USER: postgres
  MB_DB_PASS: stats
  MB_DB_HOST: {{ .Chart.Name }}-postgresql
