apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-metabase
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.metabase.port }}
