apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
data:
  LOG_URL: https://{{ .Values.viewer.url }}
  GUILD_ID: '{{ .Values.bot.guildId }}'
  MODMAIL_GUILD_ID: '{{ .Values.bot.modmailGuildId }}'
  OWNERS: '{{ .Values.bot.owners }}'
  CONNECTION_URI: mongodb://root:modmail@{{ .Chart.Name }}-mongodb:27017
  
  MODMAIL_VIEWER_URL: https://{{ .Values.viewer.url }}
  MODMAIL_VIEWER_MONGODB_URI: mongodb://root:modmail@{{ .Chart.Name }}-mongodb:27017
  MODMAIL_VIEWER_DISCORD_OAUTH_CLIENT_ID: '{{ .Values.viewer.oauthClientId }}'
  MODMAIL_VIEWER_DISCORD_GUILD_ID: '{{ .Values.bot.guildId }}'
  MODMAIL_VIEWER_HTTP_PORT: '{{ .Values.viewer.port }}'
