apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.viewer.url }}
      http:
        paths:
          - path: '/'
            pathType: Prefix
            backend:
              service:
                name: {{ .Chart.Name }}-viewer
                port:
                  number: {{ .Values.viewer.port }}
