enabled: true
database:
  # Can be "mongodb" or "postgresql"
  type: 'mongodb'
  host: '{{ .Release.Name }}-{{ .Values.database.type }}'
  username: ''
  password: ''
  passwordSecret: "{{ .Release.Name }}-{{ .Values.database.type }}"
  dbName:
awsSecretName: 'quilt-backups'
endpoint: 'https://s3.eu-central-003.backblazeb2.com'
